import random

R_EATING=" I Don't eat obsiously as I am a Bot"
R_HELLO = "Satshri-akal🙏 ji ----- Dso ki sewa kra😁"
R_OWNER=" Arshpreet Singh😎\nGurtaj Singh🥰\nGurneet Singh🤩\nMankirat Singh😉 are my owner"
R_R="Guru Nanak Dev Engineering College, one of the prestigious, oldest and minority institution of Northern India, was established under the aegis of Nankana Sahib Education Trust (NSET) in 1956. NSET was founded in memory of the most sacred temple of Nankana Sahib, birth place of Guru Nanak Dev Ji. Shiromani Gurudwara Prabandhak Committee, Amritsar, a premier organization of universal brotherhood, which is the main force behind the mission of ""Removal of Economic Backwardness through Technology"" and NSET with the same mission, established a Polytechnic in 1953 and Guru Nanak Dev Engineering College (GNDEC) in 1956. The Trust deed was registered on 24th February 1953 with a commitment by Nankana Sahib Education Trust to uplift the vast weaker section of Indian polity comprising Rural India by admitting 70% students every year from Rural Areas. This commitment was made to the nation on 8th April, 1956. The day when foundation stone of the College was laid by Late Dr. Rajendra Prasad Ji, the First President of India."
R_P="Dr. Sehijpal Singh Guru Nanak Dev Engineering College, Ludhiana (an autonomous college under UGC Act), established in 1956, was set up under the aegis of Nankana Sahib Education Trust, devoted to the cause of rural education to meet the growing demand for technical and professional manpower and industries. We are proud that this institution has consistently maintained its tradition of excellence in the field of technical education till date. The college has been declared an Autonomous College by UGC, New Delhi on 17.8.2012. The college has privilege of starting Ph.D degree under Quality Improvement Programme (QIP) by AICTE, New Delhi. The college has been accredited with A Grade by NAAC. The college has attained ISO 9001:2015 Certification and the UG programmes are accredited by IEI."
R_V=" Realization of Glimpses of a Golden India in the real(rural) India which lives and abounds in its villages. GNDEC will excel nationally and distinguish itself as a recognized pre-eminent leader to serve this 70% Brotherhood through its socioeconomic upliftment by exposure of the havenots to Engg. & Technology thereby grooming them as technically competent and intellectually-vital Graduates through practically focused quality learning experiences, and thus assuring productive Careers for them."
R_M="Upliftment of Rural Students through technical education.Respond to local societal needs by developing selected targeted research projects.Quality training programs in need based modern technology.To maintain state-of-the-art infrastructure in laboratories.To promote culture of self-employment.To impart non-formal education to unemployed youth./nTo inculcate moral, ethical, spiritual values in education at all levels."
R_C = "Guru Nanak Dev Engineering College campus is spread over 86 acres of prime land about 5 Kms from Bus Stand and 8 Kms from Ludhiana Railway Station on Ludhiana-Malerkotla Road. The college campus is well planned with beautifully laid out tree plantation,pathways,flowerbeds besides the well maintained sprawling lawns all around. It has beautiful building for College, Hostels, Swimming Pool, Sports and Gymnasium Hall Complex, Gurduwara Sahib, Bank, Dispensery, Post Office, Open Air Theatre. There are three hostels for boys and one for girls with a total accomodation of about 1200 students.These hostels are provided with all amenities and basic services.The greenery of the campus is remarkable and special care is being taken to preserve it."
def unknown():
    response = ['Could you please re-phrase that?',
                "...",
                "Sounds about right",
                "what does that mean?"][random.randrange(4)]
    return response            